.github/workflows/ci.yml, .github/workflows/docker.yml, .github/workflows/release.yaml, Dockerfile.sbom_db, Makefile
dependabot skipped sbom_db dockerfile updates (see https://github.com/cisco-open/kubei/pull/117) , moving dockerfile to root folder to be with all other dockerfiles.
=> fix: move sbom db dockerfile to root

charts/kubeclarity/templates/deployment.yaml, charts/kubeclarity/values.yaml
This PR provides the option to use the official Postgres Container Image.
This requires a small change in deployment.yaml for the image of the initContainer.
How to use official Postgres image:
```yaml
kubeclarity-postgresql:
postgresqlDataDir: "/data/pgdata"
persistence:
mountPath: "/data"
image:
repository: postgres
tag: 11.16-alpine3.16
securityContext:
enabled: true
fsGroup: 70
containerSecurityContext:
enabled: true
runAsUser: 70
```
=> Helm Chart: Fix to use official Postgresql Container image instead of Bitnami image

charts/kubeclarity/templates/deployment.yaml
This PR addresses three issues:
1. increase security by enforcing readonly filesystems in initcontainers and do not allow privilege escalation
2. Explicitly set `privileged: false` in order to be "compliant" to [kubeaudit](https://github.com/Shopify/kubeaudit) rules.
3. Use [official curl container image](https://hub.docker.com/r/curlimages/curl/tags) instead of [yauritux/busybox-curl](https://hub.docker.com/r/yauritux/busybox-curl)
- official image instead of potential not-trustworthy source
- Init containers run as uid=1001 while curl executable in `yauritux/busybox-curl` can only be run as root user. See file permissions from container: 
```
$ docker run --rm -ti yauritux/busybox-curl /bin/sh
/home # which curl
/bin/curl
/home # ls -las /bin/curl
3376 -rwxr--r--    1 root     root …
```
=> Helm Chart: InitContainers: additional securityContext attributes and official curl image

e2e/cli_scan_test.go, shared/pkg/config/analyzer.go, shared/pkg/converter/cyclonedx_to_syft.go, shared/pkg/formatter/cyclonedx.go, shared/pkg/scanner/grype/common.go
When processing a scratch container with no dependencies the generated SBOM has no components. This PR adds a few commits that fix issues identified when trying to scan those SBOMs.
=> Workaround issue processing scratch containers with no components in SBOM

backend/pkg/rest/applications_controller_test.go
Sorting sub-fields inside of the sort function passed to sort.Slice doesn't work because that function may not be called for every entry depending on the sort algorithm. This commit moves the sort for the sub-fields outside of parent sort.
=> Ensure application controller UTs sort before assert correctly

cli/cmd/analyze.go, runtime_k8s_scanner/pkg/analyze/analyze.go, shared/pkg/analyzer/analyzer.go, shared/pkg/analyzer/cdx_gomod/cyclonedx_gomod.go, shared/pkg/analyzer/merge.go, shared/pkg/analyzer/merge_test.go, shared/pkg/analyzer/purl.go, shared/pkg/analyzer/syft/syft.go, shared/pkg/analyzer/trivy/trivy.go, shared/pkg/config/gomod.go, shared/pkg/config/syft.go, shared/pkg/config/trivy.go
This PR includes several commits to improve the analyzer SBOM merging logic, removing the need for extra encode/decode operations, and also handling some of the more complex fields in the components so that information isn't lost during the merge.
=> Improve analyzer SBOM merging

shared/pkg/converter/cyclonedx.go
A bug in the format enum String() function resulted in the default output format being cyclonedx-xml instead of cyclonedx-json. This commit fixes that bug.
=> Fix regression on cyclonedx JSON format

Dockerfile.backend, Dockerfile.cis_docker_benchmark_scanner, Dockerfile.cli, Dockerfile.runtime_k8s_scanner, Dockerfile.sbom_db
Moving the docker ARG directives to where they are required prevents docker re-evaulating all the steps in the Dockerfile when the args change.
Adding Dockerfile buildkit caches to the go build step prevents the need for go to recompile everything on every build, and also removes the need to put separate layers for `go mod download`.
https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/reference.md#run---mount
Without this PR:
`make docker` on a fresh system (docker system prune -a): 38 mins
`make docker` again with a small edit in shared/: 35 mins
With this PR:
`make docker` on a fresh system: 14mins
`make docker` again with a small edit in shared/: 1 min 30 seconds
=> Improve Docker build performance when re-running builds

backend/pkg/database/common.go, backend/pkg/database/id_view.go
If an Application has no vulnerabilties or packages, when filtering on that ApplicationID through the API, the API would return everything instead of filtering to nothing. This ensures that if you filter on ApplicationID which doesn't match anything, then the API returns no results.
=> Fix issue filtering on ApplicationID with no packages or vuls

shared/pkg/analyzer/trivy/trivy.go
Trivy analyzer should also detect programming language dependencies.
=> Fix trivy analyzer detects only os packages

shared/pkg/scanner/trivy/scanner.go
trivy PrimaryURL is a link to avd.aquasec.com, which aggregates links we already have in vul.Vulnerability.References (and other information about vulnerability). It would be more logical for me to use References instead of PrimaryURL.
=> Use trivy vul References instead of PrimaryURL

charts/kubeclarity/values.yaml
Update curl image to a non vulnerable image
```
$ grype --add-cpes-if-none --only-fixed docker.io/curlimages/curl:7.84.0
✔ Vulnerability DB        [no update available]
New version of grype is available: 0.55.0 (currently running: 0.52.0)
✔ Loaded image
✔ Parsed image
✔ Cataloged packages      [21 packages]
✔ Scanned image           [4 vulnerabilities]
NAME          INSTALLED  FIXED-IN   TYPE  VULNERABILITY   SEVERITY
libcrypto1.1  1.1.1p-r0  1.1.1q-r0  apk   CVE-2022-2097   Medium
libssl1.1     1.1.1p-r0  1.1.1q-r0  apk   CVE-2022-2097   Medium
zlib          1.2.12-r1  1.2.12-r2  apk   CVE-2022-37434  Critical
```
```
$ grype --add-cpes-if-none --only-fixed docker.io/curlimages/curl:7.87.0
✔ Vulnerability DB        [no update available]
New version of grype is available: 0.55.0 …
```
=> update curl image tag to 7.87.0 (latest)

backend/go.mod, backend/go.sum, backend/pkg/backend/backend.go, backend/pkg/config/config.go, backend/pkg/metrics/README.md, backend/pkg/metrics/alertmanager-kubeclarity.yaml, backend/pkg/metrics/kubeclarity-dashboard.json, backend/pkg/metrics/prometheus_metrics.go, charts/kubeclarity/templates/deployment.yaml, charts/kubeclarity/values.yaml
This PR will add a /metrics endpoint to KubeClarity. It needs to be enabled with a config value, with a default of not being enabled. 
In order to expose metrics from KubeClarity to Prometheus, you need to enable
the endpoint by setting the environment variable `PROMETHEUS_REFRESH_INTERVAL_SECONDS`
to value larger than zero, for instance 300 which means that the Prometheus endpoint will get updated values every 5 minutes.
KubeClarity uses healthz for readiness / liveness, and as the metrics is added with `http.Handle("/metrics", promhttp.Handler())`, this will make it live on port 8081.
I have added an Alertmanager example, and a Grafana dashboard.
This PR will close #63
=> Add support for exposing Prometheus metrics endpoint

charts/kubeclarity/templates/_helpers.tpl, charts/kubeclarity/templates/ingress.yaml, charts/kubeclarity/templates/service.yaml, charts/kubeclarity/values.yaml
Hello everyone. 
I know there is no authentication yet on Kubeclarity, but I needed an ingress to be able to reach my Kubeclarity instance through an hostname, only reachable when connected to a VPN.
I tried to make retrocompatible changes and it shouldn't impact current helm deployments.
I tried this on my side (GKE) and can now:
- Access the UI with an hostname
- Access the backend in my CI/CD pipelines through the hostname
On my environment, a VPN is needed to reach the Kubeclarity instance.
Please let me know modifications I may have to make. 
Thanks everyone for your comments.
=> helm: adding the possibility to create an ingress

backend/pkg/metrics/README.md, backend/pkg/metrics/alertmanager-kubeclarity.yaml, backend/pkg/metrics/kubeclarity-dashboard.json, backend/pkg/metrics/prometheus_metrics.go
2 things changed with this PR:
1: It turns out that I cannot use label "severity" as it clashes with the following, making alerts complain:
https://github.com/prometheus-operator/kube-prometheus/blob/0ac0d7f9bf5ab1de3e596ff3bdd4b36c52e27267/jsonnet/kube-prometheus/components/alertmanager.libsonnet#L52
This makes alert complain: `"vector contains metrics with the same labelset after applying alert labels"`
Renaming the label `severity` to `vul_severity` to avoid this.
2: Added an initial call to `s.recordVulnerabilities` in order to prime the metrics at startup. Otherwise, metrics will make a dip to zero upon server restart.
=> Prometheus metrics improvements

README.md, charts/kubeclarity/values.yaml, cli/go.mod, cli/go.sum, runtime_k8s_scanner/go.mod, runtime_k8s_scanner/go.sum, shared/go.mod, shared/go.sum
Picks up grype-server version v0.1.5 that contains CPE matching configuration fix for the remote grype scanner.
=> Bump grype-server to pick up CPE matching fix

.github/PULL_REQUEST_TEMPLATE.md, .github/stale.yml, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md
This also enables the stalebot for managing old issues.
=> Update documentation to align with cisco-open templates

CONTRIBUTING.md, cis_docker_benchmark_scanner/pkg/scanner/run.go, e2e/common/api.go, e2e/curl_nginx.yaml, e2e/runtime_scan_test.go
Solve an index out of range crash in `createDockleConfig` when `scanConfig.Registry.Auths` is empty
[X] Bug Fix
[ ] Refactor
=> fix an index out of range in createDockleConfig

.github/PULL_REQUEST_TEMPLATE.md
This results in a task list being generated for the PR which doesn't make sense because in most cases you aren't going to select all the options.
[ ] Bug Fix
[ ] Refactor
[X] Documentation
=> Remove bullet list from "Type of Change" section in PR template

shared/pkg/analyzer/purl.go, shared/pkg/analyzer/purl_test.go
Fixes a panic which occurs if an input which is a valid URL doesn't have either 2 or 3 parts to the opaque once split.
The only valid lengths for PURL opaques once split are 2 and 3, so this PR returns an empty PURL if the PURL being parsed is invalid.
[X] Bug Fix
[ ] Refactor
=> Fix panic while parsing PURLs

.github/stale.yml
The current messaging doesn't provide information about how to un-stale an issue or the time scales for when the issue will move into stale/closed. This commit updates the messaging to make it more approachable.
[ ] Bug Fix
[ ] Refactor
[X] Documentation
=> Update stalebot message to explain how to keep an issue alive

runtime_scan/pkg/scanner/scanner.go
Check if `killSignal` channel is closed to avoid panic calling close it twice.
[x] Bug Fix
[ ] Refactor
=> Check killSignal channel is closed

charts/kubeclarity/values.yaml, cli/go.mod, shared/pkg/scanner/grype/common.go, shared/pkg/scanner/grype/local_grype.go
The PR is setting the `NormalizeByCVE` to true in grype `VulnerabilityMatcher` to orient results by CVE instead of the original vulnerability ID when possible.
Also, replacing the `FindVulnerabilitiesForPackage` deprecated function in grype.
[ ] Bug Fix
[X] New Feature
[ ] Refactor
=> feat(grype): normalize matches by CVE

Dockerfile.backend, Dockerfile.cis_docker_benchmark_scanner, Dockerfile.cli, Dockerfile.runtime_k8s_scanner, Dockerfile.sbom_db, README.md, charts/kubeclarity/values.yaml, cli/go.mod, cli/go.sum, runtime_k8s_scanner/go.mod, runtime_k8s_scanner/go.sum, shared/go.mod, shared/go.sum, shared/pkg/scanner/trivy/scanner.go
The PR bumps trivy to release version v0.41.0 and also aligned the trivy server image to the same version.
Also, bump golang builder.
[ ] Bug Fix
[ ] Refactor
[X] Other (bump deps)
=> Bump trivy to v0.41.0 and golang builder

charts/kubeclarity/templates/scanner-template-configmap.yaml, charts/kubeclarity/values.yaml, runtime_scan/pkg/scanner/job_managment.go, runtime_scan/pkg/scanner/job_managment_test.go
The PR adds a support to be able to set the default namespace where job scanners should run.
If a default value is set it may be overridden if:
1. The scanner job must run in the pod namespace to fetch image pull secrets, OR
2. The scanner job must run in the release namespace to fetch service credentials (more info in https://github.com/openclarity/kubeclarity#private-registries-support-for-k8s-runtime-scan)
Solves https://github.com/openclarity/kubeclarity/issues/389
[ ] Bug Fix
[X] New Feature
[ ] Refactor
=> Add a support to set the default scanners namepace

shared/pkg/scanner/dependency_track/api/client/models/vulnerability.go, shared/pkg/scanner/dependency_track/api/swagger.yaml
Scan using dependency_track integration fails, e.g.:
```
SCANNER_DEPENDENCY_TRACK_DISABLE_TLS=true \
SCANNER_DEPENDENCY_TRACK_HOST=dependency-track-apiserver.dependency-track \
SCANNER_DEPENDENCY_TRACK_API_KEY=XXX \
./cli scan nginx.sbom -i sbom
...
ERRO[0150] failed to get vulnerabilities result: failed to get vulnerabilities by project: json: cannot unmarshal string into Go struct field Vulnerability.published of type float64  app=kubeclarity scanner=dependency-track
...
````
This is minimal changes to fix dependency_track scanner integration.
[X] Bug Fix
[ ] Refactor
=> Update dependency track swagger specification

ui/src/components/Form/form-fields/TextField/index.js, ui/src/components/Form/validators.js, ui/src/layout/RuntimeScan/ScanConfiguration/ScanOptionsForm.js, ui/src/layout/RuntimeScan/ScanConfiguration/ScheduleScanForm/index.js
Initially the UI allowed negative entries to be entered in the Max Scan Parallelism (under the scan configuration). This is not valid since negative numbers for parallelism  (e.g. Max Scan Parallelism = -20) do not make sense and are not valid according to the API spec. After this change, UI will allow only positive entries to be entered. This fixes #441.
[x] Bug Fix
[ ] Refactor
=> Add min value validation on Max Scan Parallelism field

shared/pkg/utils/cyclonedx_helper/cyclonedx_helper.go, shared/pkg/utils/cyclonedx_helper/cyclonedx_helper_test.go
Fix empty package licenses bug. This prefers license ID when exist, and will use the license name if present in case there is no ID
=> Fix empty licenses bug: Use license name when there is no ID

runtime_scan/pkg/scanner/scanner.go
avoid injecting the same volumeMount path.
It can happen if the list of imagePullSecrets on the pod holds the same secret name more than once.
[ *] Bug Fix
[ ] Refactor
=> avoid duplicate image pull secrets

.github/workflows/docker.yml, .github/workflows/release.yaml
This commit adds granular permissions to the workflows that need them to perform their tasks.
The release action needs access to the "contents" of a repo in order to create a release, and requires access to packages in order to publish the containers.
The docker action only needs access to packages to publish the "latest" build from the main branch.
[ ] Bug Fix
[ ] Refactor
[X] Other (please describe) CI/CD
=> Add granular permissions to GitHub action workflows

README.md, shared/pkg/config/remote_grype.go, shared/pkg/scanner/grype/remote_grype.go
I would like to be able to work with HTTPS remote Grype server. My change adds the option to configure https through: SCANNER_REMOTE_GRYPE_SERVER_SCHEMES
[ ] Bug Fix
[*] New Feature
[ ] Refactor
- [*] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [*] Existing issues have been referenced (where applicable)
- [*] I have verified this change is not present in other open pull requests
- [*] Functionality is documented
- [*] All code style checks pass
- [*] New code contribution is covered by automated tests
- [*] All new and existing tests pass
=> custom schemes available from env vars

shared/pkg/analyzer/syft/syft.go, shared/pkg/scanner/grype/common.go, shared/pkg/utils/image_helper/image_helper.go, shared/pkg/utils/image_helper/image_helper_test.go
The PR fixes an issue with local images sbom generation.
Following syft update in https://github.com/anchore/syft/pull/1846/files#diff-2a232ddbaede1f8b49a67d5e38d543dc3bf7869661f6910ce00dc6a024af6b75, when a local image was scanned, the manifest digest is now missing in the `version`.
There was a need to get the manifest digest if repo digest is missing when getting the image hash.
Before this PR the sbom for local image (`docker.io/idanfrim/kubeclarity-cli:local`) was created with the following `metadata.component`
```
"component": {
"bom-ref": "87162f89d41584fc",
"type": "container",
"name": "docker.io/idanfrim/kubeclarity-cli",
"version": "local"
}
``` 
After the fix, the `metadata.component` is
```
"component": {
"bom-ref": "87162f89d41584fc",
"type": "container",
"name": …
```
=> fix(syft): get hash from repo or manifest digest to support local images

shared/pkg/utils/image_helper/image_helper.go
Following https://github.com/openclarity/kubeclarity/pull/487, github.com/google/go-containerregistry version was update from `v0.14.0` to `v0.16.1`. 
The code [here](https://github.com/google/go-containerregistry/pull/1130/files) introduce a change in classification of empty layers in the docker history commands.
The PR here uses the RawConfigFile() since the logic maintains the old behavior. In addition we will return empty commands in the future if such mismatch happen again.
[X] Bug Fix
[ ] Refactor
=> fix: use RawConfigFile() instead of ConfigFile() to get docker image config file

.golangci.yml, Makefile, backend/pkg/config/config.go, backend/pkg/database/new_vulnerability.go, backend/pkg/database/package.go, cis_docker_benchmark_scanner/pkg/config/config.go, cli/pkg/config/registry.go, runtime_k8s_scanner/pkg/config/config.go, sbom_db/backend/pkg/config/config.go, shared/pkg/config/gomod.go, shared/pkg/config/runtime_scanner.go, shared/pkg/utils/cyclonedx_helper/cyclonedx_helper.go
This version contains a number of fixes and ensures that it works for golang 1.21+.
The depguard and tagalign linters were added since 1.52.x which are temporarily disabled as former seems to be usefull, but requires a discussion with the team before enabling it while, the latter does not seem to provide much of a value besides making the structs with struct tags a bit more readable/organized.
There are several fixes and nolint comments that were added to address lint issues identified by the new version.
[ ] Bug Fix
[ ] Refactor
[X] Other (please describe) Linter bump
=> chore: Bump golangci-lint to 1.54.2

e2e/cli_scan_test.go, e2e/go.mod, e2e/go.sum, shared/pkg/analyzer/trivy/trivy.go, shared/pkg/scanner/trivy/scanner.go, shared/pkg/utils/trivy/dboptions.go
The java db repo value was missing in the trivy db options, the PR adds the missing configuration both in the analyzer and the scanner configuration.
Resolves https://github.com/openclarity/kubeclarity/issues/488
[X] Bug Fix
[ ] Refactor
=> fix(trivy): add java db repo default configuration for trivy analyzer and scanner

e2e/cli_scan_test.go, shared/pkg/analyzer/merge.go, shared/pkg/analyzer/merge_test.go, shared/pkg/analyzer/syft/syft.go, shared/pkg/analyzer/trivy/trivy.go, shared/pkg/analyzer/trivy/trivy_test.go, shared/pkg/scanner/grype/common.go, shared/pkg/scanner/grype/common_test.go, shared/pkg/scanner/grype/test_data/nginx.results.json, shared/pkg/scanner/trivy/scanner.go, shared/pkg/utils/image_helper/image_helper.go, shared/pkg/utils/image_helper/image_helper_test.go
The PR fixes an issue with local images sbom generation, when analyzing a local image the RepoDigests are missing so there is a need to use a common hash for the artifact, the code here takes the image ID (https://github.com/opencontainers/image-spec/blob/main/config.md/#imageid) as the identifier since it exists in both trivy and syft.
The PR fixes https://github.com/openclarity/kubeclarity/issues/498 and also update the changes done in https://github.com/openclarity/kubeclarity/pull/497
[X] Bug Fix
[ ] Refactor
=> fix: get local image hash from ImageID when RepoDigest is missing

charts/kubeclarity/templates/_helpers.tpl, charts/kubeclarity/templates/ingress.yaml, charts/kubeclarity/templates/servicemonitor.yaml, charts/kubeclarity/values.yaml
Update the servicemonitor helm template to give the possibility to add extra labels which is basically required when using Prometheus since it needs a label named `release` to be able to scrap metrics.
Also updating the nginx helm template to be able to add extra labels
Tested the changes using the helm template command and all tests passed 
[ ] Bug Fix
[ ] Refactor
- [X ] All new and existing tests pass
=> feat(helm): add extra labels for servicemonitor and ingress

backend/cmd/backend/main.go, backend/pkg/backend/backend.go, backend/pkg/config/config.go, backend/pkg/database/database.go, charts/kubeclarity/templates/deployment.yaml, charts/kubeclarity/values.yaml
This adds a configuration option to set the sslMode when connecting to the backend database. It was previously hard-coded to "disable" in the connection string.
[ ] Bug Fix
[ ] Refactor
=> feat: add config for the DB SSL mode

charts/kubeclarity/templates/deployment.yaml, charts/kubeclarity/templates/grype_server/deployment.yaml, charts/kubeclarity/templates/sbom_db/deployment.yaml, charts/kubeclarity/templates/scanner-template-configmap.yaml, runtime_scan/pkg/config/scanner_template.go, runtime_scan/pkg/scanner/job_managment_test.go
The [pod security standard](https://kubernetes.io/docs/concepts/security/pod-security-standards/) (PSS) level `restricted` enforces to have
```yaml
securityContext:
capabilities:
drop: [ALL]
```
set for all containers. At least with Kyverno, this check is case sensitive, so our Kubeclarity pods are rejected. Until now, this is set to lower case `all` in the Helm chart templates. This change capitalizes every `all` to `ALL` to be pedantically conformant with PSS.
I guess it would be more flexible to have these settings as defaults in the chart values, instead of hard-coding. If you wish, I am happy to change that, too.
=> fix(helm): Capitalize `capabilities.drop[]` due to PSS

Dockerfile.backend, Dockerfile.cis_docker_benchmark_scanner, Dockerfile.cli, Dockerfile.runtime_k8s_scanner, Dockerfile.sbom_db
This reverts commit 6f29bd6c06e2d0dbf1cbb35bd1e7a0a6df312107.
This fixes the build issues found in the `kubeclarity` and `sbom-db` images.
=> Revert "build(deps): bump golang from 1.21.3-alpine to 1.21.5-alpine (#568)"

.github/workflows/image-cleanup.yml
Fix image cleanup workflow failing with `error: invalid value '' for '--token <TOKEN>': The `token` value is not valid. Must be $GITHUB_TOKEN, a classic personal access token (prefixed by 'ghp') or oauth token (prefixed by 'gho').` 
https://github.com/openclarity/openclarity/actions/workflows/image-cleanup.yml
=> fix(ci): use github token instead of pat in image cleanup workflow

api/types/asset.go, provider/aws/discoverer/discoverer.go
Currently when the orchestrator finds a VM, it fails to create a new `VMInfo` because the architecture field is empty. So, we need to provide the option of `Unknown` architecture when parsing it.
Cheers to @akijakya for finding this issue!
=> fix(api): empty arch failure when vm discovered

cli/cmd/asset/asset_create.go, cli/cmd/asset/asset_scan_create.go, cli/cmd/convert/convert.go, cli/cmd/root/root.go, cli/cmd/scan/scan.go, cli/presenter/openclarity.go, cli/state/openclarity.go, cli/state/openclarity_test.go, cli/test/boot/README.md, cli/test/boot/vagrant/cloud-config.cfg
- This PR migrates the `convert` command from KubeClarity.
- While I was working on this, I changed `VMClarity` references to `OpenClarity` ones
=> feat(cli): migrate KubeClarity command

.github/workflows/dependencies.yml, Makefile, makefile.d/20-tools.mk, renovate.json
This PR adds support for using self-hosted Renovate to perform dependency sync. The benefit is that we can now define post-dependency update commands to e.g. format and regenerate code.
Renovate Bot will be replaced with OpenClarity Bot to track dependency data in GitHub.
=> feat(ci): add support for self-hosted renovate

e2e/config/config.go, e2e/full_scan_test.go, plugins/runner/internal/runtimehandler/docker/handler.go
https://github.com/openclarity/openclarity/issues/760
* Fix mount definition when volume type mount is required
* Fix volume read permissions
* Enable plugins scan in full scan e2e test for Docker, AWS, GCP and Azure
✅ Tests successful on Docker and AWS
=> fix(plugin): full scan run with plugins enabled 

.github/workflows/dependencies.yml, Makefile, renovate.json
The PR limit per hour was 2 dependency updates + there was an option enabled to only create PRs when scheduled or set in the dashboard. Since we manage the schedule ourselves, we need to remove the renovate-service schedule (otherwise you can only have dep PRs created if you mark the checkbox in the dashboard). Another PR might be needed depending on how Renovate dashboard reacts with the new changes
=> fix(workflow): reconfigure renovate dependency tracker

Makefile, e2e/config/config.go, e2e/config/config_test.go, e2e/full_scan_test.go, e2e/kics_test.go, testenv/azure/asset.go
* Run cloud end-to-end test suite with latest images in the registry
* Disable malware for cloud runs due to long scan times
* KICS e2e test will not run on a certain provider so only enable this test when for Docker
* Increase time to process findings for Azure
* Change VM image scanned on Azure
=> refactor(e2e): improve

Makefile, e2e/config/config.go, e2e/config/config_test.go, testenv/config.go
- shorten testenv names because some generated resource names in GCP would sometimes exceed a limit, causing the deployment to fail; also the `openclarity` in the name was redundant.
- increased timeout to ensure full test to finish
=> refactor(e2e): improve GCP e2e test env

e2e/full_scan_test.go, testenv/docker/asset/docker-compose.override.yml, testenv/kubernetes/asset/deployment.go
Adding assertions for findings of different families. We might build our own vulnerable image and use that as an asset to assert more later.
=> test(e2e): assert presence of more finding types

provider/kubernetes/scanner/scanner.go
Change image used to download assets to `curlimages/curl:latest` as suggested at https://github.com/openclarity/openclarity/issues/886
Cheers to @duckman for finding and reporting this issue!
=> feat(k8s): use scanner image with arm64 support

cli/presenter/writer_test.go, scanner/families/sbom/types/result.go
Fixes #885 
We can now return an empty byte slice from the parser if there are no SBOM results.
=> fix(cli): check SBOM result before writing

ui/src/layout/AssetScans/AssetScansTable.jsx, ui/src/layout/Assets/AssetsForFindingTable.jsx, ui/src/layout/Assets/AssetsTable.jsx
Fixed issue with broken UI app when assets don't have image information
#906 
| Before | After |
| :---: | :---: |
|![image](https://github.com/user-attachments/assets/cb6b0748-26fd-4feb-a2a2-744f7eee0af1)  | ![image](https://github.com/user-attachments/assets/f353c0f7-5264-476b-b18c-c9fbcfcd5f75) ![image](https://github.com/user-attachments/assets/da137ec6-33cd-4309-abdd-3055c8c8562d) |
=> fix(ui): Fixed issue with blank page when `image` information is missed in assetInfo

installation/kubernetes/helm/openclarity/templates/apiserver/deployment.yaml
Fix the following error due to extra curly brackets:
│     * Deployment.apps "openclarity-apiserver" is invalid: [spec.template.spec.containers[0].env[3].valueFrom.secretKeyRef.name: Invalid value: "openclarity }}": a lowercase RFC 1123 subdomain must consist of l │
=> fix(helm): installation error with externalPostgresql

.github/workflows/dependencies.yml
Dependencies workflow needs `go` which is removed with the cleanup step (added with https://github.com/openclarity/openclarity/pull/964)
=> ci(ci): setup go in dependencies workflow
