openclarity/openclarity

README.md
minor text corrections to Readme.
=> Small textual corrections to README.md

README.md
Add documentation for the required K8s permissions
=> Add required permissions description to readme

deploy/kubei.yaml
=> add cpu and memory resources for clair, db and kubei

pkg/orchestrator/job-manager.go, pkg/orchestrator/job-manager_test.go
Report scan failure when job creation failed
Fix bug in job name creation when image name used digest and not tag
=> digest image name support

README.md, deploy/kubei.yaml, pkg/config/scan_config.go, pkg/scanner/job-manager.go
=> Make scanner service account configurable

README.md, deploy/kubei.yaml, pkg/config/scan_config.go, pkg/scanner/job-manager.go
=> Add insecure reg support

pkg/webapp/view.html
Close https://github.com/Portshift/kubei/pull/64
Thanks @viallikavoo
=> Fix Typo in webapp

.github/CODEOWNERS, .github/dependabot.yml, .github/settings.yml, Dockerfile, README.md, cmd/kubei/main.go, go.mod, pkg/orchestrator/orchestrator.go, pkg/scanner/job-manager.go, pkg/scanner/scanner.go, pkg/webapp/webapp.go
- go.mod: Update module name to `github.com/cisco-open/kubei`
- .github: Add default repo configuration files
Signed-off-by: Stephen Augustus <foo@auggie.dev>
=> go.mod: Update module name to `github.com/cisco-open/kubei`

.github/settings.yml
Signed-off-by: Stephen Augustus <foo@auggie.dev>
=> .github: Update repo name to `kubeclarity`

charts/kubeclarity/templates/deployment.yaml, charts/kubeclarity/values.yaml
=> feat(charts): resource limits

charts/kubeclarity/templates/scanner-template-configmap.yaml, charts/kubeclarity/values.yaml
fixes https://github.com/openclarity/kubeclarity/issues/183
=> feat(helm): make scanner pods tolerations configurable

charts/kubeclarity/templates/deployment.yaml, charts/kubeclarity/values.yaml
=> feat: allow to define podAnnotations for kubeclarity pod

README.md
Signed-off-by: Peter Balogh <p.balogh.sa@gmail.com>
related: #225
=> docs(cli): local image scan and private registry support

sbom_db/backend/pkg/backend/run.go, sbom_db/backend/pkg/database/database.go
Signed-off-by: Peter Balogh <p.balogh.sa@gmail.com>
=> Fix (sbomdb): db log level

backend/pkg/database/database.go
Fixes https://github.com/openclarity/kubeclarity/issues/249 and https://github.com/openclarity/kubeclarity/issues/247.
=> fix(backend): clear views before auto migrate

backend/cmd/backend/main.go, backend/pkg/backend/backend.go, backend/pkg/config/config.go, backend/pkg/database/application.go, backend/pkg/database/database.go, backend/pkg/database/fake.go, backend/pkg/database/full_tree.go, backend/pkg/database/join_tables.go, backend/pkg/database/new_vulnerability.go, backend/pkg/database/package.go, backend/pkg/database/refresh_materialized_views.go, backend/pkg/database/resource.go, backend/pkg/database/scheduler.go, backend/pkg/database/vulnerability.go, charts/kubeclarity/templates/deployment.yaml, charts/kubeclarity/values.yaml, e2e/cli_scan_test.go, e2e/common/consts.go, e2e/common/utils.go, e2e/main_test.go, e2e/runtime_scan_test.go, e2e/testvalues.yaml
Signed-off-by: Peter Balogh <p.balogh.sa@gmail.com>
fixes: #226
=> Backend: in case of PosrtgreSQL use materialized views 

e2e/cli_scan_test.go
This test is to ensure that we don't regress on the fix for scanning SBOMs which have no components in them.
=> Add e2e regression test for image with no components

charts/kubeclarity/templates/scanner-template-configmap.yaml
=> fix: allow setting proxies when trivy is disabled

shared/pkg/scanner/grype/local_grype.go
In Grype v0.50.0 they made CPE based matching configurable, the CLI defaults to true, but the booleans in the code default to false. This commit re-enables the CPE based matching for all the package types supported by Grype.
=> Enable CPE matching in Grype local

ui/src/layout/ApplicationResources/ApplicationResourcesTable.js, ui/src/layout/Applications/ApplicationsTable.js, ui/src/layout/Packages/PackagesTable.js, ui/src/layout/Vulnerabilities/VulnerabilitiesTable.js
Make all UI tables sorted by vulnerability severity by default
=> Add a default sort by vulnerability severity to all tables in UI

runtime_scan/pkg/config/scan_config.go, runtime_scan/pkg/config/scanner_template.go
Resolves https://github.com/openclarity/kubeclarity/issues/327
=> Delete unused config load

.github/workflows/ci.yml, README.md
Adding uninstall using helm section to the README.
In addition i've ignored `md` files from running the CI workflow, for next time.
[ ] Bug Fix
[ ] Refactor
[X] Documentation
=> docs: Add uninstall using helm section to the readme

.github/workflows/skip-ci.yml
The PR adds a ci skip workflow to handle md files and the required checks.
[ ] Bug Fix
[ ] Refactor
[X] Other (workflow)
=> workflow: add skip ci workflow to handle md files checks

ui/package-lock.json, ui/package.json
UI - resolve webpack vulnerability
[x] Bug Fix
[ ] Refactor
=> UI - resolve webpack vulnerability

ui/src/components/Table/index.js, ui/src/components/TablePage/index.js, ui/src/context/FiltersProvider.js, ui/src/layout/App/index.js, ui/src/layout/ApplicationResources/ApplicationResourcesTable.js, ui/src/layout/ApplicationResources/index.js, ui/src/layout/Applications/ApplicationsTable.js, ui/src/layout/Applications/index.js, ui/src/layout/Dashboard/FixableVulnerabilitiesWidget/index.js, ui/src/layout/Dashboard/PackagesPieWidget/index.js, ui/src/layout/Dashboard/TopVulnerabilitiesWidget/index.js, ui/src/layout/Packages/PackageDetails/TabResources.js, ui/src/layout/Packages/PackagesTable.js, ui/src/layout/Packages/index.js, ui/src/layout/Packages/utils.js, ui/src/layout/RuntimeScan/SeverityFilterAndCountersSteps/index.js, ui/src/layout/Vulnerabilities/VulnerabilitiesTable.js, ui/src/layout/Vulnerabilities/index.js, ui/src/layout/Vulnerabilities/utils.js
ui - save current page on drilldown + fix filters const name
[ ] Bug Fix
[ ] Refactor
=> ui - save current page on drilldown

ui/package-lock.json, ui/package.json, ui/src/components/SystemFilterDisplay/index.js, ui/src/components/TablePage/index.js, ui/src/context/FiltersProvider.js, ui/src/layout/ApplicationResources/utils.js, ui/src/layout/Applications/utils.js, ui/src/layout/Packages/utils.js, ui/src/layout/RuntimeScan/SeverityFilterAndCountersSteps/index.js, ui/src/layout/Vulnerabilities/utils.js
Filters in the UI will update page's URL
https://github.com/openclarity/kubeclarity/issues/392
[] Bug Fix
[ ] Refactor
=> UI - filters in URL support

ui/package-lock.json, ui/package.json, ui/src/components/CopyButton/index.js, ui/src/components/Filter/index.js, ui/src/components/TablePage/index.js
Added a copy filters button to the UI
[ ] Bug Fix
[ ] Refactor
=> UI filters copy button

charts/kubeclarity/values.yaml
small change in comment in values.yaml
[ ] Bug Fix
[ ] Refactor
[* ] Documentation
=> fix:(nit) trivy analyzer instead of scanner in comment

charts/kubeclarity/templates/_helpers.tpl, charts/kubeclarity/templates/clusterrole.yaml, charts/kubeclarity/templates/clusterrolebinding.yaml, charts/kubeclarity/templates/deployment.yaml, charts/kubeclarity/templates/ingress.yaml, charts/kubeclarity/templates/role.yaml, charts/kubeclarity/templates/rolebinding.yaml, charts/kubeclarity/templates/scanner-template-configmap.yaml, charts/kubeclarity/templates/secret.yaml, charts/kubeclarity/templates/service.yaml, charts/kubeclarity/templates/serviceaccount.yaml
Change regarding feedback in https://github.com/openclarity/kubeclarity/pull/452
[x] Refactor
=> Updated label helper to improve usability

.github/workflows/ci.yml, .github/workflows/skip-ci.yml
This adds the merge_group trigger to the CI workflows to ensure they run as part of the merge queue.
[ ] Bug Fix
[ ] Refactor
[X] Other (please describe)
=> Update CI workflow to enable support for merge queues

backend/go.mod, backend/go.sum, cis_docker_benchmark_scanner/go.mod, cis_docker_benchmark_scanner/go.sum, cli/go.mod, cli/go.sum, e2e/go.mod, e2e/go.sum, runtime_k8s_scanner/go.mod, runtime_k8s_scanner/go.sum, runtime_scan/go.mod, runtime_scan/go.sum, shared/go.mod, shared/go.sum
Closes  #546 #547 #548 #549 #550 #551 #552
=> build(deps): bump github.com/docker/docker from 24.0.5+incompatible to 24.0.7+incompatible

charts/kubeclarity/templates/grype_server/service.yaml, charts/kubeclarity/templates/sbom_db/service.yaml, charts/kubeclarity/templates/secret.yaml, charts/kubeclarity/templates/service.yaml
Closes #555 . Alternatively, it could also be an option if required.
[ ] Bug Fix
[x] Refactor
=> fix(helm): remove `helm.sh/hook` annotations

.github/CODEOWNERS
=> chore(general): update codeowners

api/server/go.mod, uibackend/server/go.mod
=> build(api,uibackend): fix incorrect go.mod replace

installation/kubernetes/helm/openclarity/templates/ui/service.yaml
=> fix(helm): fix service port

installation/kubernetes/helm/openclarity/README.md, installation/kubernetes/helm/openclarity/values.yaml
=> chore(helm): set postgres resource preset explicitly

installation/kubernetes/helm/openclarity/Chart.lock, installation/kubernetes/helm/openclarity/Chart.yaml, installation/kubernetes/helm/openclarity/README.md, installation/kubernetes/helm/openclarity/templates/apiserver/deployment.yaml, installation/kubernetes/helm/openclarity/templates/apiserver/pvc.yaml, installation/kubernetes/helm/openclarity/values.yaml
=> feat(helm): add option for all supported databases

ui/src/api/constants.ts, ui/src/components/DetailsPageWrapper/index.jsx, ui/src/components/WizardModal/index.jsx, ui/src/layout/AssetScans/AssetScanDetails.jsx, ui/src/layout/Assets/AssetDetails.jsx, ui/src/layout/Dashboard/FindingsImpactWidget/index.jsx, ui/src/layout/Dashboard/FindingsTabsWidget/index.jsx, ui/src/layout/Dashboard/RiskiestAssetsWidget/index.jsx, ui/src/layout/Findings/FindingsDetailsPage.jsx, ui/src/layout/Scans/Configurations/ConfigurationActionsDisplay/index.jsx, ui/src/layout/Scans/Configurations/ConfigurationDetails/index.jsx, ui/src/layout/Scans/ScanConfigWizardModal/index.jsx, ui/src/layout/Scans/Scans/ScanActionsDisplay/index.jsx, ui/src/layout/Scans/Scans/ScanDetails.jsx, ui/src/layout/Scans/Scans/ScansTable.jsx
This PR removes the custom queries and replaces it with TanStack queries. The only remaining query is the query in the Table component which will be removed when we rework the whole Table component next.
=> feat(ui): custom queries on the frontend

Makefile, e2e/config/config.go, e2e/config/config_test.go, installation/aws/OpenClarity.cfn, testenv/aws/aws.go, testenv/aws/config.go, testenv/aws/utils.go, testenv/azure/azure.go, testenv/azure/config.go, testenv/azure/utils.go, testenv/gcp/config.go, testenv/gcp/gcp.go, testenv/gcp/utils.go
Some minor improvements to prepare for adding cloud e2e tests to the CI pipeline (currently not planned).
=> feat(testenv): cloud e2e test improvements

CONTRIBUTING.md, GOALS.md, RELEASE.md, SECURITY.md, containerruntimediscovery/server/crio/discoverer.go
Update VMClarity references to OpenClarity
=> docs(general): update docs vm references to openclarity

.github/workflows/build-and-push-components.yml
=> ci(general): set up qemu

.github/workflows/pr.yml
Fixes https://github.com/openclarity/openclarity/issues/834
=> fix(ci): PR size labeler

api/client/go.mod, api/server/go.mod, api/types/go.mod, cli/go.mod, containerruntimediscovery/client/go.mod, containerruntimediscovery/server/go.mod, containerruntimediscovery/types/go.mod, e2e/go.mod, installation/go.mod, orchestrator/go.mod, plugins/runner/go.mod, plugins/sdk-go/example/go.mod, plugins/store/kics/go.mod, provider/go.mod, scanner/go.mod, testenv/go.mod, uibackend/client/go.mod, uibackend/server/go.mod, utils/go.mod, versions.yaml
=> release(general): prepare version v1.0.0

Makefile
Revert changes to sed command in distribution targets.
https://github.com/openclarity/openclarity/actions/runs/11273692903/job/31351263046
=> fix(ci): sed command fails in release wf

README.md
=> docs(general): update slack link

installation/kubernetes/helm/openclarity/templates/apiserver/deployment.yaml
=> fix(helm): external postgresql port quotes

api/client/go.mod, api/server/go.mod, api/types/go.mod, cli/go.mod, containerruntimediscovery/client/go.mod, containerruntimediscovery/server/go.mod, containerruntimediscovery/types/go.mod, e2e/go.mod, installation/go.mod, orchestrator/go.mod, plugins/runner/go.mod, plugins/sdk-go/example/go.mod, plugins/store/kics/go.mod, provider/go.mod, scanner/go.mod, testenv/go.mod, uibackend/client/go.mod, uibackend/server/go.mod, utils/go.mod, versions.yaml
=> release(general): prepare release v1.1.0

scanner/families/sbom/types/result.go
https://github.com/openclarity/openclarity/issues/885
=> fix(scanner): panic when nil result

.github/workflows/pr.yml
The PR scopes can be a bit more loosely defined to allow more expressions on commits rather than being code/area specific.
=> fix(ci): drop explicit PR scope check

api/client/go.mod, api/server/go.mod, api/types/go.mod, cli/go.mod, containerruntimediscovery/client/go.mod, containerruntimediscovery/server/go.mod, containerruntimediscovery/types/go.mod, e2e/go.mod, installation/go.mod, orchestrator/go.mod, plugins/runner/go.mod, plugins/sdk-go/example/go.mod, plugins/store/kics/go.mod, provider/go.mod, scanner/go.mod, testenv/go.mod, uibackend/client/go.mod, uibackend/server/go.mod, utils/go.mod, versions.yaml
=> release(general): prepare release v1.1.1

.github/workflows/build-and-push-components.yml, .github/workflows/build-and-upload-components.yml
Create cache directory if cache not found for input keys.
=> fix(ci): cache dir not found

renovate.json
* Re-enable the dependency dashboard
* Old dashboard https://github.com/openclarity/openclarity/issues/792
=> chore(deps): enable renovate dashboard

containerruntimediscovery/server/containerd/discoverer.go, installation/kubernetes/helm/openclarity/README.md, installation/kubernetes/helm/openclarity/templates/cr-discovery-server/daemonset.yaml, installation/kubernetes/helm/openclarity/values.yaml
du to this issue, i have made socket configurable and add value to helm chart
https://github.com/openclarity/openclarity/issues/913
=> feat(containerruntimediscovery): add configurable socket

api/client/go.mod, api/server/go.mod, api/types/go.mod, cli/go.mod, containerruntimediscovery/client/go.mod, containerruntimediscovery/server/go.mod, containerruntimediscovery/types/go.mod, e2e/go.mod, installation/go.mod, orchestrator/go.mod, plugins/runner/go.mod, plugins/sdk-go/example/go.mod, plugins/store/kics/go.mod, provider/go.mod, scanner/go.mod, testenv/go.mod, uibackend/client/go.mod, uibackend/server/go.mod, utils/go.mod, versions.yaml
=> release(general): prepare release v1.1.2

installation/kubernetes/helm/openclarity/README.md, installation/kubernetes/helm/openclarity/templates/cr-discovery-server/daemonset.yaml, installation/kubernetes/helm/openclarity/values.yaml
=> fix(containerruntimediscovery): env var assignment in CR discovery daemonset

installation/kubernetes/helm/openclarity/README.md, installation/kubernetes/helm/openclarity/templates/cr-discovery-server/daemonset.yaml, installation/kubernetes/helm/openclarity/values.yaml
Allow container runtime paths to be overriden via values.
=> feat(charts): Allow container runtime paths to be overriden via values

api/client/go.mod, api/server/go.mod, api/types/go.mod, cli/go.mod, containerruntimediscovery/client/go.mod, containerruntimediscovery/server/go.mod, containerruntimediscovery/types/go.mod, e2e/go.mod, installation/go.mod, orchestrator/go.mod, plugins/runner/go.mod, plugins/sdk-go/example/go.mod, plugins/store/kics/go.mod, provider/go.mod, scanner/go.mod, testenv/go.mod, uibackend/client/go.mod, uibackend/server/go.mod, utils/go.mod, versions.yaml
=> release(release): prepare version v1.1.3
